app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type: annotation

places:
    type:     rest
    resource: AppBundle\Controller\PlaceController

prices:
    type:     rest
    resource: AppBundle\Controller\Place\PriceController

themes:
    type:     rest
    resource: AppBundle\Controller\Place\ThemeController

users:
    type:     rest
    resource: AppBundle\Controller\UserController

preferences:
    type:     rest
    resource: AppBundle\Controller\User\PreferenceController

auth-tokens:
    type:     rest
    resource: AppBundle\Controller\AuthTokenController

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
