app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type: annotation

places:
    type:     rest
    resource: AppBundle\Controller\PlaceController

prices:
    type:     rest
    resource: AppBundle\Controller\Place\PriceController

themes:
    type:     rest
    resource: AppBundle\Controller\Place\ThemeController

users:
    type:     rest
    resource: AppBundle\Controller\UserController
