# src/AppBundle/Resources/config/serialization.yml
AppBundle\Entity\Place:
    attributes:
        id:
            groups: ['place', 'price']
        name:
            groups: ['place', 'price']
        address:
            groups: ['place', 'price']
        prices:
            groups: ['place']
        themes:
            groups: ['place']

AppBundle\Entity\Price:
    attributes:
        id:
            groups: ['place', 'price']
        type:
            groups: ['place', 'price']
        value:
            groups: ['place', 'price']
        place:
            groups: ['price']

AppBundle\Entity\Theme:
    attributes:
        id:
            groups: ['place', 'theme']
        name:
            groups: ['place', 'theme']
        value:
            groups: ['place', 'theme']
        place:
            groups: ['theme']

AppBundle\Entity\User:
    attributes:
        id:
            groups: ['user', 'preference']
        firstname:
            groups: ['user', 'preference']
        lastname:
            groups: ['user', 'preference']
        email:
            groups: ['user', 'preference']
        preferences:
            groups: ['user']

AppBundle\Entity\Preference:
    attributes:
        id:
            groups: ['user', 'preference']
        name:
            groups: ['user', 'preference']
        value:
            groups: ['user', 'preference']
        user:
            groups: ['preference']
